if(NOT ZLIB_FOUND)
  message(STATUS "Executing FindZLIB, since ZLIB_FOUND is not set. ZLIB_LIBRARY: ${ZLIB_LIBRARY}")
  include(${CMAKE_ROOT}/Modules/FindZLIB.cmake)
  message(STATUS "After FindZLIB; ZLIB_LIBRARY: ${ZLIB_LIBRARY}")
endif()
